spring:
  cloud:
    gateway:
      routes:

        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://mall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: order_route
          uri: lb://mall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: coupon_route
          uri: lb://mall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}


        - id: admin_route
          uri: lb://mall-administration
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/mall-administration/$\{segment}


        - id: shop_host_route
          uri: lb://mall-product
          predicates:
            - Host=mall.com,item.mall.com

        - id: shop_search_route
          uri: lb://mall-search
          predicates:
            - Host=search.mall.com

        - id: shop_auth_route
          uri: lb://mall-auth-server
          predicates:
            - Host=auth.mall.com

        - id: shop_cart_route
          uri: lb://mall-cart
          predicates:
            - Host=cart.mall.com

        - id: shop_order_route
          uri: lb://mall-order
          predicates:
            - Host=order.mall.com

        - id: shop_member_route
          uri: lb://mall-member
          predicates:
            - Host=member.mall.com

        - id: shop_seckill_route
          uri: lb://mall-seckill
          predicates:
            - Host=seckill.mall.com
