spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://43.138.22.205:3306/mall_sms?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 43.138.22.205:8123
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719
  application:
    name: mall-coupon
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 43.138.22.205
  session:
    store-type: redis



mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.wang.killshop: info
server:
  port: 4000

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

