spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8123
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719
    alicloud:
      access-key: LTAI5tMY3XCViuBmUUKpe9Vt
      secret-key: qZaFHaeMURnJND3NjvajbFTmEZ8PT8
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: mall2023



#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
